import 'package:flutter/material.dart';
import 'package:pirate_app/providers/product.dart';

List<Product> dummy_products = [
  Product(
    id: "1",
    title: "Luffy Hat",
    price: 12.67,
    description: "A Hat is a crucial piece of a Pirate's look",
    imageUrl:
        "https://i.postimg.cc/J40GNPgv/Pin-Clipart-com-pirate-sword-clip-art-5419166.png",
    color: const Color(0xFF3D82AE),
    genre: "Hat",
  ),
  Product(
    id: "2",
    title: "Pirate Ship Medium",
    price: 260,
    description: "A Ship",
    imageUrl:
        "https://cdn.pixabay.com/photo/2017/02/01/00/29/sailing-ship-2028575_1280.png",
    color: const Color(0xFFD3A984),
    genre: "Ship",
  ),
  Product(
    id: "3",
    title: "Robe",
    price: 234,
    description: "A Robe",
    imageUrl:
        "https://static.wikia.nocookie.net/clubpenguin/images/9/97/Gray_Pirate_Coat_icon.png/revision/latest?cb=20140203183823",
    color: const Color(0xFF989493),
    genre: "Dress",
  ),
  Product(
    id: "4",
    title: "Pirate Sword",
    price: 160,
    description: "A Sword",
    imageUrl: "https://i.postimg.cc/Hk55M68H/pngwing-com.png",
    color: const Color.fromARGB(255, 154, 199, 108),
    genre: "Weapon",
  ),
  Product(
    id: "5",
    title: "Pirate Pistol",
    price: 234,
    description: "A Pistol",
    imageUrl: "https://i.postimg.cc/g2hrXhWY/download-removebg-preview-3.png",
    color: const Color(0xFF989493),
    genre: "Weapon",
  ),
  Product(
    id: "6",
    title: "Pirate Sword",
    price: 275,
    description: "A Sword",
    imageUrl: "https://i.postimg.cc/hjvBxFd9/download-removebg-preview-4.png",
    color: const Color(0xFFD3A984),
    genre: "Weapon",
  ),
  Product(
    id: "7",
    imageUrl: "https://i.postimg.cc/26pTDh7g/download-removebg-preview-1.png",
    title: "Blue Hat",
    price: 100.33,
    description: "A Hat",
    color: const Color(0xFFD3A984),
    genre: "Hat",
  ),
  Product(
    id: "8",
    imageUrl: "https://i.postimg.cc/kMQY71Zs/download-removebg-preview.png",
    title: "Black Hat",
    price: 120,
    description: "A Hat",
    color: const Color(0xFF989493),
    genre: "Hat",
  ),
  Product(
    id: "9",
    imageUrl: "https://i.postimg.cc/BbwfNm2d/download-removebg-preview-2.png",
    title: "Pirate Ship Small",
    price: 200,
    description: "A Ship",
    color: const Color(0xFF989493),
    genre: "Ship",
  ),
  Product(
    id: "10",
    imageUrl: "https://i.postimg.cc/qBtrvT0r/images-removebg-preview.png",
    title: "Pirate Ship Large",
    price: 380,
    description: "A Ship",
    color: const Color(0xFF3D82AE),
    genre: "Ship",
  ),
  Product(
    id: "11",
    title: "Red Robe",
    price: 150,
    description: "A Robe",
    imageUrl:
        "https://i.postimg.cc/cJ0vYJhP/Whats-App-Image-2022-05-14-at-9-36-45-PM-removebg-preview.png",
    color: const Color(0xFF3D82AE),
    genre: "Dress",
  ),
  Product(
    id: "12",
    title: "Blue Robe",
    price: 305,
    description: "A Robe",
    imageUrl:
        "https://i.postimg.cc/2yQ6VRvC/Whats-App-Image-2022-05-14-at-9-36-45-PM-1-removebg-preview.png",
    color: const Color(0xFFD3A984),
    genre: "Dress",
  ),
  Product(
    id: "13",
    title: "Brown Robe",
    price: 283,
    description: "A Robe",
    imageUrl:
        "https://i.postimg.cc/T34R2YSr/Whats-App-Image-2022-05-14-at-9-36-44-PM-removebg-preview.png",
    color: const Color.fromARGB(255, 154, 199, 108),
    genre: "Dress",
  ),
  Product(
    id: "14",
    title: "Brown Hat",
    price: 234,
    description: "A Hat",
    imageUrl: "https://i.postimg.cc/rmTvfbsP/download-removebg-preview-5.png",
    color: const Color.fromARGB(255, 154, 199, 108),
    genre: "Hat",
  ),
  Product(
    id: "15",
    title: "Cannon",
    price: 354,
    description: "A Cannon",
    imageUrl: "https://i.postimg.cc/g0mDQPy8/images-removebg-preview-1.png",
    color: const Color(0xFF3D82AE),
    genre: "Weapon",
  ),
  Product(
    id: "16",
    title: "BattleShip",
    price: 540,
    description: "A Ship",
    imageUrl: "https://i.postimg.cc/t4TPxCzr/images-removebg-preview-2.png",
    color: const Color.fromARGB(255, 154, 199, 108),
    genre: "Ship",
  ),
];
